apiVersion: v1
kind: ConfigMap
metadata:
  name: templatebotaide
data:
  # These configurations are injected as environment variables into the
  # sqrbot app container.
  API_LSST_CODES_PROFILE: "production"
  REGISTRY_URL: "http://localhost:8081"
  KAFKA_BROKER: "localhost:9092"
  KAFKA_PROTOCOL: "PLAINTEXT"
  # Schema registry subject configuration
  SQRBOTJR_SUBJECT_SUFFIX: ""
  SQRBOTJR_SUBJECT_COMPATIBILITY: "FORWARD_TRANSITIVE"
