apiVersion: v1
kind: ConfigMap
metadata:
  name: templatebotaide
data:
  # These configurations are injected as environment variables into the
  # sqrbot app container.
  API_LSST_CODES_PROFILE: "production"
  REGISTRY_URL: "http://localhost:8081"
  KAFKA_BROKER: "localhost:9092"
  KAFKA_PROTOCOL: "PLAINTEXT"
  # Schema registry subject configuration
  TEMPLATEBOT_SUBJECT_SUFFIX: ""
  # Topic names
  TEMPLATEBOT_TOPIC_PRERENDER: 'templatebot.prerender'
  TEMPLATEBOT_TOPIC_RENDERREADY: 'templatebot.render-ready'
  TEMPLATEBOT_TOPIC_POSTRENDER: 'templatebot.postrender'
  # Kafka consumer group ID
  TEMPLATEBOT_GROUP_ID: 'templatebot-aide'
