sudo: required
dist: xenial
services:
  - docker
language: python
matrix:
  include:
    - python: "3.7.1"
      env: DEPLOY_DOCKER_IMAGE=true
install:
  - "make install"
script:
  - "make test"
  - "make image"
after_success:
  # Docker Hub (no-op for PRs and DEPLOY_DOCKER_IMAGE=false)
  - make travis-docker-deploy
env:
  global:
    - DEPLOY_DOCKER_IMAGE=false  # disable docker push in regular test matrix
    # DOCKER_USERNAME
    - secure: "QW5ZhNRJsg4i7y2Lmu6zJu5TrJcP3Ut/Xvt86q1cAWtLBD1e3r61ess/WR6B5lpmbAKqCC1EFNNNFGAASyKqSN2JlTEKNtfmzFXRhlFDYpmmxYUIiYlgjnC7h0XETTEsW5pOKNs+TcUP13cwNL7OL7YzaYDlb87Zt4QAlJ5ZSsShtJgQpgT+zhcvOxJPgcyDCzWYsi1Cww78GCzigi0WixeFw/+wWwBMFwUOhbZGmITnMGoanCpS/6HvaQ7X9X29+esaGh6BrMAnlDF6Suq9bSbe5x0T7qSA7HylhneLmgRMF2GYe25ky4eG6IdqtAVSYm8dhhON3PCrAKbqJ8Q9RuefL7bzi/tK5pX66sXSQObBTXWogT8N0zuriQoH5yVskDwl+3Hb3Flfr85fmlkk7prAw4dxgz88ilkTjNHgBRqi80096BhmOksIcH/ysTYyVNf4wQmcBuiGoAxlE9INUlsKgMTpEpNFk2M4yLNV9wf2nh0SEc9n6zIrhPPPZuQYMAkMQr/1wCGfJ5IbY8h6Rqynx08CmGKCrxn4MFDasBk/IXzcKhNgiL+602JaLkzqOmI7BL5RIhs6vFnXwAoCmzrfZ3FcyZjktpTeIwUvzylIHjy+ie5OTYz5INSmkEzO2ADvCI+BWsAlRC0cbvMKPOy75MmUti/MAk//FftDefc="
    # DOCKER_PASSWORD
    - secure: "W0nUxTMwk9A4wGKlSBfdy6g9LRBElUcgozZnXdNJoNvPS7B3Sxxe8aeWwYnQt4Vj4X4o5pELUvZ5Mbd/JMPef/4+Yl4qJ3UCCuntS3hWz70d0WRuCMrHBf4Oc1XutnHRd7MuQM44Lf69LOTVxxS2B4y1kuVKGuMB67buSe8uDsBkTkNEUJHQJjwO31FjxakqUGrse0+VRDYqi+yFvFggECJcAjhU2+QFX4WbRz83gTnUkssHzokN6BvnqCUZeYjPCNRgBIqEO6aXX8tyg5+6w5ohJj3Tde4gPtqZOEpNy4wV+2GpD3eb1XMWMy9VxmCOZraCreADqvsFY9bKeNSsudBFOMyiHOEEv0TMCmgyU6xhnHEECd/5HTeWUxFiqmoL+JX+qVS8Zf0LbKz/cHXQVXsjEJv2V88OfEIVJcDWJgjtVZ2gWIbMR/HyqsrT92fQtl5it/Awnv1P8LJbBPoGcyhrm/L7RdSn/koIa4zkh1nxf+YPTXYSthK8gWS7Ze3+pFUHXFk2avGosalY/fGtlg8FBwbdGA1HLA/GvMP08W/N7Uq1f7Em1LJGCezQAY//ZNViN5RL1BAMBl/CxeYSibF3FhUSQLJ4Q/PWCHv9Vnalfq6+xCcQFvl9MGyJCeYAhDYX76EmGbcsP76Q8QTxbUKiwoaDWuU5deLJ6kUhhBI="
